-- CREATE TABLE emails (
--     id BIGSERIAL PRIMARY KEY,
--     created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL DEFAULT NOW() 
--     sender VARCHAR(255) NOT NULL,
--     recipient VARCHAR(255) NOT NULL,
--     status BOOLEAN NOT NULL DEFAULT FALSE,
--     sent_time TIMESTAMP(0) WITH TIME ZONE NOT NULL DEFAULT NOW(),
--     opened BOOLEAN NOT NULL DEFAULT FALSE,
--     opened_time TIMESTAMP WITH TIME ZONE
-- )


CREATE TABLE emails (
    id BIGSERIAL PRIMARY KEY,
    created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL DEFAULT NOW(),
    sender VARCHAR(255) NOT NULL,
    body TEXT NOT NULL,
    subject VARCHAR(255) NOT NULL
);

CREATE TABLE recipients (
    id SERIAL PRIMARY KEY,
    email_id INTEGER REFERENCES emails(id),
    recipient VARCHAR(255) NOT NULL,
    status BOOLEAN NOT NULL DEFAULT FALSE,
    sent_time TIMESTAMP(0) WITH TIME ZONE NOT NULL DEFAULT NOW(),
    opened BOOLEAN NOT NULL DEFAULT FALSE,
    opened_time TIMESTAMP WITH TIME ZONE
);